name: 'backbuddy'

services:
  api:
    image: ${DOCKER_REGISTRY-}backbuddy/api:${TAG:-latest}
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: Api/Dockerfile
      args:
        BUILD_ENV: dev
    ports:
      - "8080:8080"
    env_file:
      - Development.env

  deviceorchestrator:
    image: ${DOCKER_REGISTRY-}backbuddy/deviceorchestrator:${TAG:-latest}
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build:
      context: .
      dockerfile: DeviceOrchestrator/Dockerfile
      args:
        BUILD_ENV: dev
    env_file:
      - Development.env

  mongodb:
    hostname: "mongodb"
    image: "mongo:latest"
    ports:
      - "27017:27017"
    expose:
      - "27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongodb:27017/test --quiet
      interval: 5s
      timeout: 5s
      retries: 60

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 60

  mongoexpress:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
      - ME_CONFIG_BASICAUTH=false
      - PORT=8081
    depends_on:
      mongodb: 
        condition: service_healthy

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PASSWORD=my-password
    depends_on:
      redis:
        condition: service_healthy

  firebase:
    image: spine3/firebase-emulator:latest
    ports:
      - "9000:9000"
      - "8082:8080"
      - "4000:4000"
      - "9099:9099"
      - "8085:8085"
      - "5001:5001"
      - "9199:9199"

  rabbitmq:
    image: "masstransit/rabbitmq:latest"
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q check_running && rabbitmq-diagnostics -q check_local_alarms
      interval: 5s
      timeout: 2s